# Generated by Django 3.0.5 on 2020-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['key_word'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['terms'],
            },
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=2083)),
                ('version', models.FloatField()),
                ('creation_date', models.DateTimeField(verbose_name='Date Created')),
                ('author_name', models.CharField(max_length=400)),
                ('author_contact', models.CharField(max_length=200)),
                ('num_compartments', models.PositiveSmallIntegerField()),
                ('sbml_file', models.TextField()),
                ('application', models.ManyToManyField(to='struc_model_repo.KeyWords')),
                ('terms_of_dist', models.ManyToManyField(to='struc_model_repo.TermsOfDistribution')),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
    ]
